// export const GET_PROJECTS_REQUEST = 'GET_PROJECTS_REQUEST'
// export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'
// export const GET_PROJECTS_FAIL = 'GET_PROJECTS_FAIL'

export const SOCKET_CONNECT_REQUEST = 'SOCKET_CONNECT_REQUEST'
export const SOCKET_CONNECT_SUCCESS = 'SOCKET_CONNECT_SUCCESS'
export const SOCKET_CONNECT_FAIL = 'SOCKET_CONNECT_FAIL'

export const MESSAGE_SEND = 'MESSAGE_SEND'
export const MESSAGE_GET = 'MESSAGE_GET'